# Generated by Django 4.0.1 on 2022-05-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='control.parentcategory'),
            preserve_default=False,
        ),
    ]
